-- ============================================================
-- schema.sql — TravelMate Database Schema
-- ============================================================
--
-- HOW TO USE THIS FILE:
--   This file contains SQL commands that set up your database
--   and table structure. You run it ONCE to create everything.
--
--   Option A (command line):
--     mysql -u root -p < schema.sql
--
--   Option B (inside the mysql shell):
--     mysql -u root -p
--     then: SOURCE /full/path/to/schema.sql;
--
--   Option C (MySQL Workbench):
--     Open this file and click the "Execute" (lightning bolt) button
-- ============================================================


-- ── STEP 1: CREATE THE DATABASE ──────────────────────────────
--
-- A "database" in MySQL is a container that holds tables.
-- One MySQL server can host many databases (e.g. one per project).
--
-- IF NOT EXISTS prevents an error if you run this script twice —
-- it just skips creation if "travelmate" already exists.
CREATE DATABASE IF NOT EXISTS travelmate;

-- Tell MySQL: "all the following commands apply to this database"
-- Without this, MySQL wouldn't know WHERE to create the table.
USE travelmate;


-- ── STEP 2: CREATE THE USERS TABLE (Phase 1: Registration) ──
--
-- NOTE ON ORDERING: this table is created BEFORE trips, because
-- trips.user_id is a foreign key that references users(id).
-- MySQL will reject a foreign key that points at a table which
-- doesn't exist yet, so users must always come first on a fresh
-- database.
--
-- TABLE DESIGN EXPLANATION (column by column):
--
--   id            — Unique identifier for each user.
--                    Same AUTO_INCREMENT + PRIMARY KEY pattern
--                    as the trips table.
--
--   name          — VARCHAR(100). The user's display name.
--                    100 chars is generous for any real name.
--
--   email         — VARCHAR(255). NOT NULL because every account
--                    needs one. UNIQUE means MySQL will REJECT
--                    an INSERT if that email already exists —
--                    this is our database-level safety net for
--                    "email must be unique" (in addition to the
--                    check we also do in JavaScript).
--
--   password      — VARCHAR(255). This does NOT store the real
--                    password — it stores the bcrypt HASH, which
--                    looks like "$2b$10$N9qo8uLOickgx2ZMRZoMye...".
--                    Bcrypt hashes are always 60 characters, so
--                    255 gives comfortable headroom.
--
--   created_at    — TIMESTAMP, auto-set on insert. Same pattern
--                    as trips.created_at — useful for "member
--                    since" displays later.

CREATE TABLE IF NOT EXISTS users (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(100)  NOT NULL,
  email       VARCHAR(255)  NOT NULL UNIQUE,
  password    VARCHAR(255)  NOT NULL,
  created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);


-- ── STEP 3: CREATE THE TRIPS TABLE ───────────────────────────
--
-- TABLE DESIGN EXPLANATION (column by column):
--
--   id            — Unique identifier for each trip.
--                    AUTO_INCREMENT means MySQL assigns 1, 2, 3...
--                    automatically — you never set this yourself.
--                    PRIMARY KEY means this column uniquely
--                    identifies each row (required for every table).
--
--   user_id       — INT foreign key referencing users(id). Links
--                    every trip to the account that created it.
--
--   destination   — VARCHAR(255) = variable-length text, max 255
--                    characters. Plenty for any city/country name.
--                    NOT NULL means this field is required —
--                    MySQL will reject an INSERT without it.
--
--   start_date /
--   end_date      — DATE type stores just a calendar date
--                    (no time component). MySQL stores this as
--                    'YYYY-MM-DD', matching what HTML date inputs send.
--
--   budget        — DECIMAL(10,2) stores numbers with exactly 2
--                    decimal places — perfect for money.
--                    DECIMAL is preferred over FLOAT for money
--                    because FLOAT can introduce rounding errors
--                    (e.g. 0.1 + 0.2 might not equal exactly 0.3).
--                    (10,2) means up to 10 total digits, 2 after
--                    the decimal point — max value 99999999.99
--
--   style         — VARCHAR(50). Stores values like "cultural",
--                    "foodie", etc. 50 chars is generous headroom.
--
--   days          — INT (whole number) — number of days in the trip.
--
--   summary       — VARCHAR(255). The human-readable summary line
--                    generated by itineraryEngine.js, e.g.
--                    "3-day Food & Culinary trip to Bangkok..."
--
--   budget_tier   — VARCHAR(20). Stores "low", "medium", or "high"
--                    as classified by itineraryEngine.js.
--
--   itinerary     — JSON type. Stores the entire day-by-day
--                    itinerary array as a single structured value.
--                    MySQL validates that this is well-formed JSON
--                    on insert — invalid JSON will be rejected.
--
--   created_at    — TIMESTAMP that MySQL sets AUTOMATICALLY when
--                    a row is inserted (DEFAULT CURRENT_TIMESTAMP).
--                    Useful for sorting "most recently saved first".
CREATE TABLE IF NOT EXISTS trips (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  user_id     INT           NOT NULL,
  destination VARCHAR(255)  NOT NULL,
  start_date  DATE          NOT NULL,
  end_date    DATE          NOT NULL,
  budget      DECIMAL(10,2) NOT NULL,
  style       VARCHAR(50)   NOT NULL,
  days        INT           NOT NULL,
  summary     VARCHAR(255),
  budget_tier VARCHAR(20),
  itinerary   JSON          NOT NULL,
  created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ── STEP 4 (OPTIONAL): VERIFY IT WORKED ──────────────────────
--
-- After running this file, you can check everything is correct
-- by running these commands in the mysql shell:
--
--   SHOW DATABASES;                -- should list "travelmate"
--   USE travelmate;
--   SHOW TABLES;                   -- should list "users" and "trips"
--   DESCRIBE users;                -- shows all columns and types
--   DESCRIBE trips;                -- shows all columns and types